=== aunlu/drd-hybrid/tests/found_configs/3(exmpl)/hb-config-scheme.xsd
<?xml version="1.0" encoding="utf-8" ?>

<!--
  ~ DRD - Dynamic Data Race Detector for Java programs
  ~
  ~ Copyright (C) 2002-2018 Devexperts LLC
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="HappensBeforeConfig">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Syncs" maxOccurs="1" minOccurs="1"/>
                <xs:element ref="Multiple-Syncs" maxOccurs="1" minOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Syncs">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Sync" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Multiple-Syncs">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Multiple-Sync" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Multiple-Sync">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Multiple-Links" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="Call" maxOccurs="unbounded" minOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="owner" use="required"/>
        </xs:complexType>
    </xs:element>


    <xs:element name="Multiple-Links">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Multiple-Link" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Multiple-Link">
        <xs:complexType>
            <xs:attribute name="type" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="param"/>
                        <xs:enumeration value="owner"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="args" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Call">
        <xs:complexType>
            <xs:attribute name="type" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="send"/>
                        <xs:enumeration value="receive"/>
                        <xs:enumeration value="full"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="descriptor" type="xs:string" use="required"/>
            <xs:attribute name="shouldReturnTrue" use="optional">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="true"/>
                        <xs:enumeration value="false"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="MethodCall">
        <xs:complexType>
            <xs:attribute name="owner" type="xs:string" use="required"/>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="descriptor" type="xs:string" use="required"/>
            <xs:attribute name="shouldReturnTrue" use="optional">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="true"/>
                        <xs:enumeration value="false"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="Receive">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="MethodCall" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Send">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="MethodCall" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Sync">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Links" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="Send" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="Receive" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Links">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Link" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Link">
        <xs:complexType>
            <xs:attribute name="send" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="param"/>
                        <xs:enumeration value="owner"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="send-number" type="xs:string" use="optional"/>
            <xs:attribute name="receive" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="param"/>
                        <xs:enumeration value="owner"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="receive-number" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== aunlu/drd-hybrid/tests/found_configs/3(exmpl)/hb-config-example.xml
<!--
  ~ DRD - Dynamic Data Race Detector for Java programs
  ~
  ~ Copyright (C) 2002-2018 Devexperts LLC
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->

<HappensBeforeConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:noNamespaceSchemaLocation="hb-config-scheme.xsd">
    <Syncs>
        <Sync>
            <Links>
                <Link send="owner" receive="owner"/>
                <Link send="param" send-number="0" receive="param" receive-number="0"/>
            </Links>
            <Send>
                <MethodCall owner="java.util.concurrent.ConcurrentMap" name="put"
                    descriptor="(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;"/>
            </Send>
            <Receive>
                <MethodCall owner="java.util.concurrent.ConcurrentMap" name="get"
                    descriptor="(Ljava/lang/Object;)Ljava/lang/Object;"/>
            </Receive>
        </Sync>

        <Sync>
            <Links>
                <Link send="owner" receive="owner"/>
            </Links>
            <Send>
                <MethodCall owner="java.util.concurrent.locks.Lock" name="unlock"
                    descriptor="()V"/>
            </Send>
            <Receive>
                <MethodCall owner="java.util.concurrent.locks.Lock" name="lock"
                    descriptor="()V"/>
            </Receive>
        </Sync>

        <Sync>
            <Links>
                <Link send="param" send-number="0" receive="owner"/>
            </Links>
            <Send>
                <MethodCall owner="java.util.concurrent.Executor" name="execute"
                    descriptor="(Ljava/lang/Runnable;)V"/>
            </Send>
            <Receive>
                <MethodCall owner="java.lang.Runnable" name="run"
                    descriptor="()V"/>
            </Receive>
        </Sync>
    </Syncs>

    <Multiple-Syncs>
        <Multiple-Sync owner="sun.misc.Unsafe">
            <Multiple-Links>
                <Multiple-Link type="param" args="0"/>
                <Multiple-Link type="param" args="1"/>
            </Multiple-Links>
            <Call type="full" name="compareAndSwapObject" shouldReturnTrue="true"
                descriptor="(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z"/>
            <Call type="full" name="compareAndSwapLong" shouldReturnTrue="true"
                descriptor="(Ljava/lang/Object;JJJ)Z"/>
            <Call type="full" name="compareAndSwapInt" shouldReturnTrue="true"
                descriptor="(Ljava/lang/Object;JII)Z"/>
            <Call type="receive" name="getObjectVolatile" descriptor="(Ljava/lang/Object;J)Ljava/lang/Object;"/>
            <Call type="send" name="putObjectVolatile" descriptor="(Ljava/lang/Object;JLjava/lang/Object;)V"/>
            <Call type="receive" name="getIntVolatile" descriptor="(Ljava/lang/Object;J)I"/>
            <Call type="send" name="putIntVolatile" descriptor="(Ljava/lang/Object;JI)V"/>
            <Call type="receive" name="getBooleanVolatile" descriptor="(Ljava/lang/Object;J)Z"/>
            <Call type="send" name="putBooleanVolatile" descriptor="(Ljava/lang/Object;JZ)V"/>
            <Call type="receive" name="getByteVolatile" descriptor="(Ljava/lang/Object;J)B"/>
            <Call type="send" name="putByteVolatile" descriptor="(Ljava/lang/Object;JB)V"/>
            <Call type="receive" name="getShortVolatile" descriptor="(Ljava/lang/Object;J)S"/>
            <Call type="send" name="putShortVolatile" descriptor="(Ljava/lang/Object;JS)V"/>
            <Call type="receive" name="getCharVolatile" descriptor="(Ljava/lang/Object;J)C"/>
            <Call type="send" name="putCharVolatile" descriptor="(Ljava/lang/Object;JC)V"/>
            <Call type="receive" name="getLongVolatile" descriptor="(Ljava/lang/Object;J)J"/>
            <Call type="send" name="putLongVolatile" descriptor="(Ljava/lang/Object;JJ)V"/>
            <Call type="receive" name="getFloatVolatile" descriptor="(Ljava/lang/Object;J)F"/>
            <Call type="send" name="putFloatVolatile" descriptor="(Ljava/lang/Object;JF)V"/>
            <Call type="receive" name="getDoubleVolatile" descriptor="(Ljava/lang/Object;J)D"/>
            <Call type="send" name="putDoubleVolatile" descriptor="(Ljava/lang/Object;JD)V"/>
        </Multiple-Sync>

        <Multiple-Sync owner="java.util.concurrent.locks.AbstractQueuedSynchronizer">
            <Multiple-Links>
                <Multiple-Link type="owner"/>
            </Multiple-Links>
            <Call type="receive" name="tryAcquire" descriptor="(I)Z" shouldReturnTrue="true"/>
            <Call type="send" name="tryRelease" descriptor="(I)Z"/>
            <Call type="receive" name="tryAcquireShared" descriptor="(I)Z" shouldReturnTrue="true"/>
            <Call type="send" name="tryReleaseShared" descriptor="(I)Z"/>
            <Call type="receive" name="acquire" descriptor="(I)V"/>
            <Call type="receive" name="acquireInterruptibly" descriptor="(I)V"/>
            <Call type="receive" name="tryAcquireNanos" descriptor="(IJ)Z" shouldReturnTrue="true"/>
            <Call type="send" name="release" descriptor="(I)Z"/>
            <Call type="receive" name="acquireShared" descriptor="(I)V"/>
            <Call type="receive" name="acquireSharedInterruptibly" descriptor="(I)V"/>
            <Call type="receive" name="tryAcquireSharedNanos" descriptor="(IJ)Z" shouldReturnTrue="true"/>
            <Call type="send" name="releaseShared" descriptor="(I)Z"/>
            <Call type="send" name="setState" descriptor="(I)V"/>
            <Call type="receive" name="getState" descriptor="()I"/>
            <Call type="full" name="compareAndSetState" descriptor="(II)Z" shouldReturnTrue="true"/>
        </Multiple-Sync>

        <Multiple-Sync owner="java.util.concurrent.atomic.AtomicInteger">
            <Multiple-Links>
                <Multiple-Link type="owner"/>
            </Multiple-Links>
            <Call type="receive" name="get" descriptor="()I"/>
            <Call type="send" name="set" descriptor="(I)V"/>
            <Call type="full" name="getAndSet" descriptor="(I)I"/>
            <Call type="full" name="compareAndSet" descriptor="(II)Z" shouldReturnTrue="true"/>
            <Call type="full" name="getAndIncrement" descriptor="()I"/>
            <Call type="full" name="getAndDecrement" descriptor="()I"/>
            <Call type="full" name="getAndAdd" descriptor="(I)I"/>
            <Call type="full" name="incrementAndGet" descriptor="()I"/>
            <Call type="full" name="decrementAndGet" descriptor="()I"/>
            <Call type="full" name="addAndGet" descriptor="(I)I"/>
        </Multiple-Sync>

        <Multiple-Sync owner="java.util.concurrent.atomic.AtomicLong">
            <Multiple-Links>
                <Multiple-Link type="owner"/>
            </Multiple-Links>
            <Call type="receive" name="get" descriptor="()J"/>
            <Call type="send" name="set" descriptor="(J)V"/>
            <Call type="full" name="getAndSet" descriptor="(J)J"/>
            <Call type="full" name="compareAndSet" descriptor="(JJ)Z" shouldReturnTrue="true"/>
            <Call type="full" name="getAndIncrement" descriptor="()J"/>
            <Call type="full" name="getAndDecrement" descriptor="()J"/>
            <Call type="full" name="getAndAdd" descriptor="(J)J"/>
            <Call type="full" name="incrementAndGet" descriptor="()J"/>
            <Call type="full" name="decrementAndGet" descriptor="()J"/>
            <Call type="full" name="addAndGet" descriptor="(J)J"/>
        </Multiple-Sync>

        <Multiple-Sync owner="java.util.concurrent.atomic.AtomicBoolean">
            <Multiple-Links>
                <Multiple-Link type="owner"/>
            </Multiple-Links>
            <Call type="receive" name="get" descriptor="()Z"/>
            <Call type="full" name="compareAndSet" descriptor="(ZZ)Z" shouldReturnTrue="true"/>
            <Call type="send" name="set" descriptor="(Z)V"/>
            <Call type="full" name="getAndSet" descriptor="(Z)Z"/>
        </Multiple-Sync>

        <Multiple-Sync owner="java.util.concurrent.atomic.AtomicReferenceFieldUpdater">
            <Multiple-Links>
                <Multiple-Link type="param" args="0"/>
            </Multiple-Links>
            <Call type="full" name="compareAndSet"
                descriptor="(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z" shouldReturnTrue="true"/>
            <Call type="send" name="set" descriptor="(Ljava/lang/Object;Ljava/lang/Object;)V"/>
            <Call type="receive" name="get" descriptor="(Ljava/lang/Object;)Ljava/lang/Object;"/>
            <Call type="full" name="getAndSet" descriptor="(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;"/>
        </Multiple-Sync>

        <Multiple-Sync owner="java.util.concurrent.atomic.AtomicIntegerFieldUpdater">
            <Multiple-Links>
                <Multiple-Link type="param" args="0"/>
            </Multiple-Links>
            <Call type="full" name="compareAndSet" descriptor="(Ljava/lang/Object;II)Z" shouldReturnTrue="true"/>
            <Call type="send" name="set" descriptor="(Ljava/lang/Object;I)V"/>
            <Call type="receive" name="get" descriptor="(Ljava/lang/Object;)I"/>
            <Call type="full" name="getAndSet" descriptor="(Ljava/lang/Object;I)I"/>
